version: '2'
services:
  web:
    build:
      context: .
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./media:/www/media
      - ./backups:/www/backups
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - ./docker_share:/tmp/docker_share
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
