# vivariy-site project
web:
  build: .
  volumes:
#    - /mnt/hlam/__www__/vivariy_site/app/media:/www/app/media
#    - /mnt/hlam/__www__/vivariy_site/backups:/backups
    - /www/app/media
    - /www/backups
  ports:
#    - "8003:80"
     - "80:80"
  links:
    - db
#  restart: unless-stopped
#  restart: "on-failure:20"
  restart: always


db:
  image: postgres:9.4
#  ports:
#    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: postgres
  restart: always
