version: '2'
services:
  web:
    build:
      context: .
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - /www/media
      - /www/backups
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always

