# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(help_text='Parent top-level categories', related_name='categories', to='app.TopCategory'),
        ),
    ]
