# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 07:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='faq_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Frequently asked questions (20000 symbols max)', max_length=20000, null=True, verbose_name='FAQ (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mentions_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Links to researches using this device in russian (20000 symbols max)', max_length=20000, null=True, verbose_name='Mentions (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Delivery options in russian (20000 symbols max)', max_length=20000, null=True, verbose_name='Options (ru)'),
        ),
    ]
