# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_docfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Video title (in english)', max_length=128, verbose_name='Title (en)')),
                ('title_ru', models.CharField(help_text='Video title (in russian)', max_length=128, verbose_name='Title (ru)')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Don`t show it on site')),
                ('video', models.CharField(help_text='Video embedding code from youtube.com. To obtain it, choose "share" > "embed" on youtube page with video.', max_length=1024, verbose_name='Embedding code')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.Product')),
            ],
            options={
                'verbose_name_plural': 'Youtube videos',
                'verbose_name': 'Youtube video',
            },
        ),
    ]
