# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 11:04
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160410_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='order_position',
            field=models.SmallIntegerField(default=0, help_text='Serial number in list of slides', verbose_name='Ordering position'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='Full article text (in russian)', null=True, verbose_name='Article text (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_full_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Full device description in russian (10240 symbols max)', max_length=10240, null=True, verbose_name='Full description (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mentions_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Links to researches using this device in russian (4096 symbols max)', max_length=4096, null=True, verbose_name='Mentions (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Delivery options in russian (4096 symbols max)', max_length=4096, null=True, verbose_name='Options (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Technical characteristics in russian (10240 symbols max)', max_length=10240, null=True, verbose_name='Specifications (ru)'),
        ),
    ]
