# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160417_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, help_text='Source url', max_length=1024, null=True, verbose_name='Link to source'),
        ),
    ]
