# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160521_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='error_message',
            field=models.CharField(default='', help_text='Error description (if message wasn`t sent)', max_length=4096, verbose_name='Sending error'),
        ),
    ]
