# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userrequest_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of counter', max_length=128, verbose_name='Name')),
                ('code', models.CharField(default='', help_text='Counter code. Copy there code, provided by service (google, yandex). As is.', max_length=20000, verbose_name='Code')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Counter is disabled')),
            ],
            options={
                'verbose_name': 'Analytics Counter',
                'verbose_name_plural': 'Analytics Counters',
            },
        ),
    ]
