# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 11:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160418_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faq_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Frequently asked questions (4096 symbols max)', max_length=4096, null=True, verbose_name='FAQ (ru)'),
        ),
    ]
