# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_faq_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='desc_en',
            field=models.TextField(blank=True, help_text='Company description in english (4096 symbols max)', max_length=4096, null=True, verbose_name='Description (en)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(default='', help_text='Company`s name (in english)', max_length=512, verbose_name='Name (en)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='desc',
            field=models.TextField(blank=True, help_text='Company description in russian (4096 symbols max)', max_length=4096, null=True, verbose_name='Description (ru)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(help_text='Company`s name (in russian)', max_length=512, verbose_name='Name (ru)'),
        ),
    ]
