# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_faq_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail address')),
                ('is_active', models.BooleanField(default=True, verbose_name='E-mail is active')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Subscription time')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
