# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userrequest_email_is_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Email is active')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Subscribe time')),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
                'verbose_name': 'Subscriber',
            },
        ),
    ]
